# kubectl apply -f hackaton-ui-deployement-dev.yaml
# kubectl get services --namespace=dev
# kubectl get pods --namespace=dev

apiVersion: v1
kind: Service
metadata:
  name: hackathon-ui
  namespace: dev
  labels:
    app: hackathon-ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: hackathon-ui
  # type: ClusterIP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-ui
  namespace: dev
  labels:
    app: hackathon-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-ui
  template:
    metadata:
      labels:
        app: hackathon-ui
    spec:
      containers:
      - name: hackathon-ui
        image: eu.gcr.io/cagip-hackathon-eq08-inno0-fb/hackathon-ui:latest
        imagePullPolicy: Always
        env:
        - name: VUE_APP_API_ENDPOINT
          value: "https://dev-api.julespeguet.fr"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 80
        resources:
          requests:
            cpu: "250m"
