apiVersion: v1
kind: Service
metadata:
  name: hackathon-api
  namespace: prod
  labels:
    app: hackathon-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: hackathon-api
  # type: ClusterIP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-api
  namespace: prod
  labels:
    app: hackathon-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hackathon-api
  template:
    metadata:
      labels:
        app: hackathon-api
    spec:
      containers:
      - name: hackathon-api
        image: eu.gcr.io/cagip-hackathon-eq08-inno0-fb/hackathon-api:54dc95a84fe5fa4ef0f36e5b8aaa9e3d7fe93e69
        # eu.gcr.io/cagip-hackathon-eq08-inno0-fb/hackathon-ui:latest
        env:
        - name: MONGOURI
          value: "mongodb+srv://db-test-user:GHQN7nmara10xuXv@cluster0.s6nzt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8080
        resources:
          requests:
            cpu: "250m"
      # imagePullSecrets:
      # - name: api-post-secret-github  
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hackathon-api
            topologyKey: "kubernetes.io/hostname"
